#!/usr/bin/env bash
set -euo pipefail

# Replaces the old spago.dhall conditional-source mechanism (see prior
# spago.dhall `sources` entry choosing .env.dev.purs vs .env.prod.purs based
# on env:PARTYCARLO_PROD). Copies whichever file provides `module
# PartyCarlo.Env` to src/Env.purs, which IS picked up by spago's fixed
# `src/**/*.purs` sources glob. src/Env.purs is a generated file (gitignored,
# see Step 6) and must be regenerated by this script before every
# `spago build` / `spago test` invocation.
#
# Semantics match the old Dhall check exactly: PARTYCARLO_PROD must be the
# literal string "True" to select production; anything else (including
# unset) selects dev.
cd "$(dirname "$0")/.."

if [ "${PARTYCARLO_PROD:-False}" = "True" ]; then
  cp .env.prod.purs src/Env.purs
  echo "select-env: compiling PartyCarlo.Env from .env.prod.purs (PARTYCARLO_PROD=True)"
else
  cp .env.dev.purs src/Env.purs
  echo "select-env: compiling PartyCarlo.Env from .env.dev.purs"
fi
